// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DesafioIIZetta.API.Models.Biblioteca;
using Microsoft.EntityFrameworkCore;

namespace DesafioIIZetta.API.Models;

[Table("Cliente_Livro_Emprestimo")]
public partial class ClienteLivroEmprestimo
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    public int IdCliente { get; set; }

    public int IdLivro { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DataEmprestimo { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DataDevolucaoPrevista { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataDevolucaoReal { get; set; }

    [ForeignKey("IdCliente")]
    [InverseProperty("ClienteLivroEmprestimos")]
    public virtual Cliente IdClienteNavigation { get; set; }

    [ForeignKey("IdLivro")]
    [InverseProperty("ClienteLivroEmprestimos")]
    public virtual Livro IdLivroNavigation { get; set; }
}