// <auto-generated />
using System;
using DesafioIIZetta.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DesafioIIZetta.API.Migrations
{
    [DbContext(typeof(ControleEmprestimoLivroContext))]
    partial class ControleEmprestimoLivroContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DesafioIIZetta.API.Models.Biblioteca.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Cpfcliente")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("CPFCliente");

                    b.Property<string>("EmailCliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EnderecoCliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TelefoneCliente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdCliente");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("DesafioIIZetta.API.Models.ClienteLivroEmprestimo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataDevolucaoPrevista")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataDevolucaoReal")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataEmprestimo")
                        .HasColumnType("datetime");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdLivro")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdLivro");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Cliente_Livro_Emprestimo");
                });

            modelBuilder.Entity("DesafioIIZetta.API.Models.GestaoTarefas.Tarefa", b =>
                {
                    b.Property<int>("IdTarefa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTarefa"));

                    b.Property<string>("DescricaoTarefa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("NomeTarefa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StatusTarefa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTarefa");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Tarefa");
                });

            modelBuilder.Entity("DesafioIIZetta.API.Models.GestaoTarefas.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SenhaUsuario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("DesafioIIZetta.API.Models.Livro", b =>
                {
                    b.Property<int>("IdLivro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLivro"));

                    b.Property<int>("AnoPublicacaoLivro")
                        .HasColumnType("int");

                    b.Property<string>("AutorLivro")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeEstoqueLivro")
                        .HasColumnType("int");

                    b.Property<string>("TituloLivro")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdLivro");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Livro");
                });

            modelBuilder.Entity("DesafioIIZetta.API.Models.Biblioteca.Cliente", b =>
                {
                    b.HasOne("DesafioIIZetta.API.Models.GestaoTarefas.Usuario", "Usuario")
                        .WithMany("Clientes")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Cliente_Usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DesafioIIZetta.API.Models.ClienteLivroEmprestimo", b =>
                {
                    b.HasOne("DesafioIIZetta.API.Models.Biblioteca.Cliente", "IdClienteNavigation")
                        .WithMany("ClienteLivroEmprestimos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Emprestimo_Cliente");

                    b.HasOne("DesafioIIZetta.API.Models.Livro", "IdLivroNavigation")
                        .WithMany("ClienteLivroEmprestimos")
                        .HasForeignKey("IdLivro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DesafioIIZetta.API.Models.GestaoTarefas.Usuario", "UsuarioNavigation")
                        .WithMany("Emprestimos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Emprestimo_Usuario");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdLivroNavigation");

                    b.Navigation("UsuarioNavigation");
                });

            modelBuilder.Entity("DesafioIIZetta.API.Models.GestaoTarefas.Tarefa", b =>
                {
                    b.HasOne("DesafioIIZetta.API.Models.GestaoTarefas.Usuario", "IdUsuarioNavigation")
                        .WithMany("Tarefas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Tarefa_Usuario");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("DesafioIIZetta.API.Models.Livro", b =>
                {
                    b.HasOne("DesafioIIZetta.API.Models.GestaoTarefas.Usuario", "Usuario")
                        .WithMany("Livros")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Livro_Usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DesafioIIZetta.API.Models.Biblioteca.Cliente", b =>
                {
                    b.Navigation("ClienteLivroEmprestimos");
                });

            modelBuilder.Entity("DesafioIIZetta.API.Models.GestaoTarefas.Usuario", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Emprestimos");

                    b.Navigation("Livros");

                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("DesafioIIZetta.API.Models.Livro", b =>
                {
                    b.Navigation("ClienteLivroEmprestimos");
                });
#pragma warning restore 612, 618
        }
    }
}
