// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DesafioIIZetta.API.Models;

[Table("Livro")]
public partial class Livro
{
    [Key]
    public int IdLivro { get; set; }

    [Required]
    [StringLength(150)]
    public string TituloLivro { get; set; }

    [Required]
    [StringLength(150)]
    public string AutorLivro { get; set; }

    public int AnoPublicacaoLivro { get; set; }

    public int QuantidadeEstoqueLivro { get; set; }

    [InverseProperty("IdLivroNavigation")]
    public virtual ICollection<ClienteLivroEmprestimo> ClienteLivroEmprestimos { get; set; } = new List<ClienteLivroEmprestimo>();
}